config/routes.rb
Rails.application.routes.draw do
  resources :service_events
  resources :problem_events
  get '/members/problem' => 'members#problem'
  get '/members/stat' => 'members#stat'
  get '/elevators/stat' => 'elevators#stat'
  get '/elevators/problem' => 'elevators#problem'
  get '/elevators/service' => 'elevators#service'
  resources :elevators
  resources :members
  resources :member_types
  resources :elevator_types
  resources :houses
  resources :management_companies
  get    '/login'     => 'sessions#new'
  post   '/login'     => 'sessions#create'
  # Выход
  get    '/logout'    => 'sessions#destroy'
  root 'sessions#new'
end

app/models/elevator.rb
class Elevator < ApplicationRecord
  belongs_to :house
  belongs_to :elevator_type
  belongs_to :member
end

app/models/elevator_type.rb
class ElevatorType < ApplicationRecord
end

app/controllers/elevators_controller.rb
class ElevatorsController < ApplicationController
  before_action :authorize
  before_action :set_elevator, only: [:show, :edit, :update, :destroy]

  # GET /elevators
  # GET /elevators.json
  def index
    if current_user.member_type.id == 4
      @elevators = Elevator.where(member_id: current_user.id)
    else
      @elevators = Elevator.all
    end
  end
  
  # GET /elevators/stats
  def stat
    @elevators = Elevator.all
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ReportPdf.new(t('Problem stat')+t('by elevators'), @elevators, current_user)
        send_data pdf.render, filename: t('Problem stat')+t('by elevators')+'.pdf', type: 'application/pdf'
      end
    end
  end
  
  def problem
    @elevator = Elevator.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ReportPdf.new(t('Problem stat')+t('by elevators'), @elevator, current_user)
        send_data pdf.render, filename: t('Problem stat')+'-'+@elevator.serial_number+'.pdf', type: 'application/pdf'
      end
    end
  end
  
  def service
    @elevator = Elevator.find(params[:id])
  end

  # GET /elevators/1
  # GET /elevators/1.json
  def show
  end

  # GET /elevators/new
  def new
    @elevator = Elevator.new
  end

  # GET /elevators/1/edit
  def edit
  end

  # POST /elevators
  # POST /elevators.json
  def create
    @elevator = Elevator.new(elevator_params)

    respond_to do |format|
      if @elevator.save
        format.html { redirect_to @elevator, notice: t('Elevator was successfully created') }
        format.json { render :show, status: :created, location: @elevator }
      else
        format.html { render :new }
        format.json { render json: @elevator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elevators/1
  # PATCH/PUT /elevators/1.json
  def update
    respond_to do |format|
      if @elevator.update(elevator_params)
        format.html { redirect_to @elevator, notice: t('Elevator was successfully updated') }
        format.json { render :show, status: :ok, location: @elevator }
      else
        format.html { render :edit }
        format.json { render json: @elevator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elevators/1
  # DELETE /elevators/1.json
  def destroy
    @elevator.destroy
    respond_to do |format|
      format.html { redirect_to elevators_url, notice: t('Elevator was successfully destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elevator
      @elevator = Elevator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def elevator_params
      params.require(:elevator).permit(:house_id, :elevator_type_id, :member_id, :serial_number, :commissioning_date)
    end
end

app/views/elevators/_form.html.erb
<%= form_with(model: elevator, local: true) do |form| %>
  <% if elevator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(elevator.errors.count, "error") %> prohibited this elevator from being saved:</h2>

      <ul>
      <% elevator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label t('House') %>
    <%= form.select :house_id, House.all.collect {|m| [m.address, m.id]}, {:selected => @elevator.house_id}, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label t('Elevator Type') %>
    <%= form.select :elevator_type_id, ElevatorType.all.collect {|m| [m.name, m.id]}, {:selected => @elevator.elevator_type_id}, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label t('Serial number') %>
    <%= form.text_field :serial_number, id: :serial_number, class: "form-control", placeholder: t('Input Serial number'), required: "required" %>
  </div>

  <div class="form-group">
    <%= form.label t('Member') %>
    <%= form.select :member_id, Member.where(member_type_id: 4).collect {|m| [m.full_name, m.id]}, {:selected => @elevator.member_id}, class: "form-control" %>
  </div>
    
  <div class="form-group">
    <%= form.label t('Date of commissioning') %>
    <%= form.date_field  :commissioning_date, id: :commissioning_date, class: "form-control", placeholder: t('Input Commissioning date'), required: "required" %>  
  </div>
  
  <div class="actions">
    <%= form.submit :class => "btn btn-primary" %>
  </div>
      
<% end %>

app/views/elevators/edit.html.erb
<h1><%= t('Editing Elevator') %></h1>

<%= render 'form', elevator: @elevator %>

<%= link_to t('Show'), @elevator %> |
<%= link_to t('Back'), elevators_path %>

app/views/elevators/index.html.erb
<% if notice %>
  <div class="alert alert-success" id="notice"><%= notice %></div>
<% end %>

<h1><%= t('Elevators') %></h1>


<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('House') %></th>
      <th><%= t('Elevator Type') %></th>
      <th><%= t('Serial number') %></th>
      <th><%= t('Member') %></th>
      <th><%= t('Description') %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @elevators.each do |elevator| %>
      <% cache elevator do %>
        <tr>
          <td><%= link_to elevator.house.address, elevator.house %></td>
          <td><%= link_to elevator.elevator_type.name, elevator.elevator_type %></td>
          <td><%= link_to elevator.serial_number, elevator %></td>
          <td><%= link_to elevator.member.full_name, elevator.member %></td>
          <td><%= link_to t('Show'), elevator %></td>
          <td><%= link_to t('Edit'), edit_elevator_path(elevator) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('Problem stat'), '/elevators/stat' %>

<br>

<%= link_to t('New Elevator'), new_elevator_path %>

app/views/elevators/new.html.erb
<h1><%= t('New Elevator') %></h1>

<%= render 'form', elevator: @elevator %>

<%= link_to t('Back'), elevators_path %>

app/views/elevators/problem.html.erb
<% if notice %>
  <div class="alert alert-success" id="notice"><%= notice %></div>
<% end %>

<h1><%= t('Problem stat')+t('by elevators')  %></h1>
<sapn><b><%= t('Elevator') %></b><span>
<span><%= t('Serial number') %></span>
<span><%= @elevator.serial_number %></span>
    
<h2><%= t('Not solveds') %></h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('Name') %></th>
      <th><%= t('Created At') %></th>
      <th><%= t('Problem solved?') %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% ProblemEvent.where(elevator_id: @elevator.id, solved: false).order(created_at: :desc).each do |problem_event| %>
      <tr>
        <td><%= problem_event.name %></td>
        <td><%= Time.zone.at(problem_event.created_at).strftime("%F %T") %></td>
        <td><%= problem_event.print_solved %></td>
        <td><%= link_to t('Show'), problem_event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h2><%= t('Solveds') %></h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('Name') %></th>
      <th><%= t('Created At') %></th>
      <th><%= t('Problem solved?') %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% ProblemEvent.where(elevator_id: @elevator.id, solved: true).order(created_at: :desc).each do |problem_event| %>
      <tr>
        <td><%= problem_event.name %></td>
        <td><%= Time.zone.at(problem_event.created_at).strftime("%F %T") %></td>
        <td><%= problem_event.print_solved %></td>
        <td><%= link_to t('Show'), problem_event %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<td><%= link_to t('Print as PDF'), id: @elevator.id, format: 'pdf' %></td>

app/views/elevators/service.html.erb
<% if notice %>
  <div class="alert alert-success" id="notice"><%= notice %></div>
<% end %>

<h1><%= t('Service stat') %></h1>
<sapn><b><%= t('Elevator') %></b><span>
<span><%= t('Serial number') %></span>
<span><%= @elevator.serial_number %></span>
    
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('Name') %></th>
      <th><%= t('Created At') %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% ServiceEvent.where(:elevator_id => @elevator.id).order(created_at: :desc).each do |service_event| %>
      <tr>
        <td><%= service_event.name %></td>
        <td><%= Time.zone.at(service_event.created_at).strftime("%F %T") %></td>
        <td><%= link_to t('Show'), service_event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/elevators/show.html.erb
<% if notice %>
  <div class="alert alert-success" id="notice"><%= notice %></div>
<% end %>

<h1><%= t('Elevator') %></h1>

<p>
  <strong><%= t('House') %>:</strong>
  <%= @elevator.house.address %>
</p>

<p>
  <strong><%= t('Elevator Type') %>:</strong>
  <%= @elevator.elevator_type.name %>
</p>

<p>
  <strong><%= t('Serial number') %>:</strong>
  <%= @elevator.serial_number %>
</p>

<p>
  <strong><%= t('Date of commissioning') %>:</strong>
  <%= Time.zone.at(@elevator.commissioning_date).strftime("%F") %>
</p>

<p>
  <strong><%= t('Member') %>:</strong>
  <%= @elevator.member.full_name %>
</p>

<p>
  <strong><%= t('Problem count') %>:</strong>
  <%= ProblemEvent.where(elevator_id: @elevator.id).count  %>
</p>

<p>
  <strong><%= t('Problem stat') %>:</strong>
  <%= link_to t('Show'), '/elevators/problem?id=' + @elevator.id.to_s %>
</p>

<p>
  <strong><%= t('Service count') %>:</strong>
  <%= ServiceEvent.where(elevator_id: @elevator.id).count  %>
</p>

<p>
  <strong><%= t('Service stat') %>:</strong>
  <%= link_to t('Show'), '/elevators/service?id=' + @elevator.id.to_s %>
</p>

<%= link_to t('Edit'), edit_elevator_path(@elevator) %> |
<%= link_to t('Back'), elevators_path %>

app/views/elevators/stat.html.erb
<% if notice %>
  <div class="alert alert-success" id="notice"><%= notice %></div>
<% end %>

<h1><%= t('Problem stat')+t('by elevators') %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('House') %></th>
      <th><%= t('Elevator Type') %></th>
      <th><%= t('Problem count') %></th>
      <th><%= t('Serial number') %></th>
      <th><%= t('Member') %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @elevators.each do |elevator| %>
      <% cache elevator do %>
        <tr>
          <td><%= elevator.house.address %></td>
          <td><%= elevator.elevator_type.name %></td>
          <td><%= ProblemEvent.where(elevator_id: elevator.id).count %></td>
          <td><%= elevator.serial_number %></td>
          <td><%= elevator.member.full_name %></td>
          <td><%= link_to t('Show'), '/elevators/problem?id=' + elevator.id.to_s %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<!--
<td><%= link_to t('Print as PDF'), format: 'pdf' %></td>
-->