config/routes.rb
Rails.application.routes.draw do
  resources :service_events
  resources :problem_events
  get '/members/problem' => 'members#problem'
  get '/members/stat' => 'members#stat'
  get '/elevators/stat' => 'elevators#stat'
  get '/elevators/problem' => 'elevators#problem'
  get '/elevators/service' => 'elevators#service'
  resources :elevators
  resources :members
  resources :member_types
  resources :elevator_types
  resources :houses
  resources :management_companies
  get    '/login'     => 'sessions#new'
  post   '/login'     => 'sessions#create'
  # Выход
  get    '/logout'    => 'sessions#destroy'
  root 'sessions#new'
end

app/models/service_event.rb
class ServiceEvent < ApplicationRecord
  belongs_to :elevator
  belongs_to :member
  belongs_to :problem_event
end

app/controllers/service_events_controller.rb
class ServiceEventsController < ApplicationController
  before_action :authorize
  before_action :set_service_event, only: [:show, :edit, :update, :destroy]

  # GET /service_events
  # GET /service_events.json
  def index
    if elevator_repair_specialist?
      @service_events = ServiceEvent.where(elevator_id: Elevator.where(member_id: current_user.id))
    else
      @service_events = ServiceEvent.all
    end
  end

  # GET /service_events/1
  # GET /service_events/1.json
  def show
  end

  # GET /service_events/new
  def new
    @problem_events = ProblemEvent.where("member_id = ? and planed_date <= ? or member_id = ? and planed_date IS ?", current_user.id, Time.now, current_user.id, nil)
    @service_event = ServiceEvent.new
  end

  # GET /service_events/1/edit
  def edit
    @problem_events = ProblemEvent.where("member_id = ? and planed_date <= ? or member_id = ? and planed_date IS ?", current_user.id, Time.now, current_user.id, nil)
  end

  # POST /service_events
  # POST /service_events.json
  def create
    @service_event = ServiceEvent.new(service_event_params)

    respond_to do |format|
      if @service_event.save
        format.html { redirect_to @service_event, notice: t('Service event was successfully created') }
        format.json { render :show, status: :created, location: @service_event }
      else
        format.html { render :new }
        format.json { render json: @service_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_events/1
  # PATCH/PUT /service_events/1.json
  def update
    respond_to do |format|
      if @service_event.update(service_event_params)
        ProblemEvent.find_by_id(@service_event.problem_event_id).update(solved: (params[:solved] == 'Yes'))
        format.html { redirect_to @service_event, notice: t('Service event was successfully updated') }
        format.json { render :show, status: :ok, location: @service_event }
      else
        format.html { render :edit }
        format.json { render json: @service_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_events/1
  # DELETE /service_events/1.json
  def destroy
    @service_event.destroy
    respond_to do |format|
      format.html { redirect_to service_events_url, notice: t('Service event was successfully destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_event
      @service_event = ServiceEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_event_params
      params.require(:service_event).merge!(member_id: current_user.id).permit(:elevator_id, :description, :member_id, :problem_event_id, :name)
    end
end

app/views/service_events/_form.html.erb
<%= form_with(model: service_event, local: true) do |form| %>
  <% if service_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service_event.errors.count, "error") %> prohibited this service_event from being saved:</h2>

      <ul>
      <% service_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label t('Member') %>
    <p class="form-control" readonly><%= current_user.full_name %></p>
  </div>
  
  <div class="form-group">
    <%= form.label t('Elevator') %>
    <%= form.select :elevator_id, Elevator.all.collect {|m| [m.id, m.id]}, {:selected => @service_event.elevator_id}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t("Problem Event") %>
    <%= form.select :problem_event_id, @problem_events.where(solved: false).collect {|m| [m.name, m.id]}, {:selected => @service_event.problem_event_id}, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label t('Name') %>
    <%= form.text_field :name, id: :service_event_name, class: "form-control", placeholder: t('Input Name'), required: "required" %>
  </div>
  
  <div class="form-group">
    <%= form.label t('Description') %>
    <%= form.text_area :description, id: :service_event_description, class: "form-control", placeholder: t('Input Description'), required: "required" %>
  </div>
  
  <div class="form-group">
    <%= form.label t("Problem solved?") %>
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
      <label class="btn btn-light active">
        <input type="radio" name="solved" id="solved_true" autocomplete="off" checked value='Yes'> <%= t('Yes') %>
      </label>
      <label class="btn btn-light">
        <input type="radio" name="solved" id="solved_false" autocomplete="off" value='No'> <%= t('No') %>
      </label>
    </div>
  </div>
    
  <div class="actions">
    <%= form.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/service_events/edit.html.erb
<h1><%= t('Editing Service Event') %></h1>

<%= render 'form', service_event: @service_event %>

<%= link_to t('Show'), @service_event %> |
<%= link_to t('Back'), service_events_path %>

app/views/service_events/index.html.erb
<% if notice %>
  <div class="alert alert-success" id="notice"><%= notice %></div>
<% end %>


<h1><%= t('Service Events') %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('Name') %></th>
      <th><%= t('Serial number') %></th>
      <th><%= t('Member') %></th>
      <th><%= t("Problem Event") %></th>
      <th><%= t('Description') %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_events.each do |service_event| %>
      <% cache service_event do %>
        <tr>
          <td><%= service_event.name %></td>
          <td><%= link_to service_event.elevator.serial_number, service_event.elevator %></td>
          <td><%= link_to service_event.member.full_name, service_event.member %></td>
          <td><%= link_to service_event.problem_event.name, service_event.problem_event %></td>
          <td><%= link_to t('Show'), service_event %></td>
          <td><%= link_to t('Edit'), edit_service_event_path(service_event) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('New Service Event'), new_service_event_path %>

app/views/service_events/new.html.erb
<h1><%= t('New Service Event') %></h1>

<%= render 'form', service_event: @service_event %>

<%= link_to t('Back'), service_events_path %>

app/views/service_events/show.html.erb
<% if notice %>
  <div class="alert alert-success" id="notice"><%= notice %></div>
<% end %>

<h2><%= @service_event.name %></h2>

<p>
  <strong><%= t('Address') %>:</strong>
  <%= @service_event.elevator.house.address %>
</p>

<p>
  <strong><%= t('Elevator') %>:</strong>
  <%= @service_event.elevator.elevator_type.name %>
</p>

<p>
  <strong><%= t('Description') %>:</strong>
  <%= @service_event.description %>
</p>

<p>
  <strong><%= t('Member') %>:</strong>
  <%= @service_event.member.full_name %>
</p>

<p>
  <strong><%= t('Problem Event') %>:</strong>
  <%= link_to @service_event.problem_event.name, @service_event.problem_event %>
</p>

<%= link_to t('Edit'), edit_service_event_path(@service_event) %> |
<%= link_to t('Back'), service_events_path %>