config/routes.rb
Rails.application.routes.draw do
  resources :service_events
  resources :problem_events
  get '/members/problem' => 'members#problem'
  get '/members/stat' => 'members#stat'
  get '/elevators/stat' => 'elevators#stat'
  get '/elevators/problem' => 'elevators#problem'
  get '/elevators/service' => 'elevators#service'
  resources :elevators
  resources :members
  resources :member_types
  resources :elevator_types
  resources :houses
  resources :management_companies
  get    '/login'     => 'sessions#new'
  post   '/login'     => 'sessions#create'
  # Выход
  get    '/logout'    => 'sessions#destroy'
  root 'sessions#new'
end

app/controllers/elevator_types_controller.rb
class ElevatorTypesController < ApplicationController
  before_action :authorize
  before_action :set_elevator_type, only: [:show, :edit, :update, :destroy]

  # GET /elevator_types
  # GET /elevator_types.json
  def index
    @elevator_types = ElevatorType.all
  end

  # GET /elevator_types/1
  # GET /elevator_types/1.json
  def show
  end

  # GET /elevator_types/new
  def new
    @elevator_type = ElevatorType.new
  end

  # GET /elevator_types/1/edit
  def edit
  end

  # POST /elevator_types
  # POST /elevator_types.json
  def create
    @elevator_type = ElevatorType.new(elevator_type_params)

    respond_to do |format|
      if @elevator_type.save
        format.html { redirect_to @elevator_type, notice: t('Elevator type was successfully created') }
        format.json { render :show, status: :created, location: @elevator_type }
      else
        format.html { render :new }
        format.json { render json: @elevator_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elevator_types/1
  # PATCH/PUT /elevator_types/1.json
  def update
    respond_to do |format|
      if @elevator_type.update(elevator_type_params)
        format.html { redirect_to @elevator_type, notice: t('Elevator type was successfully updated') }
        format.json { render :show, status: :ok, location: @elevator_type }
      else
        format.html { render :edit }
        format.json { render json: @elevator_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elevator_types/1
  # DELETE /elevator_types/1.json
  def destroy
    @elevator_type.destroy
    respond_to do |format|
      format.html { redirect_to elevator_types_url, notice: t('Elevator type was successfully destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elevator_type
      @elevator_type = ElevatorType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def elevator_type_params
      params.require(:elevator_type).permit(:name, :load_carrying_capacity, :nominal_speed, :factory_manufacturer)
    end
end

app/helpers/elevator_types_helper.rb
module ElevatorTypesHelper
end

app/views/elevator_types/_form.html.erb
<%= form_with(model: elevator_type, local: true) do |form| %>
  <% if elevator_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(elevator_type.errors.count, "error") %> prohibited this elevator_type from being saved:</h2>

      <ul>
      <% elevator_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label t('Name') %>
    <%= form.text_field :name, id: :elevator_type_name, class: "form-control", placeholder: t('Input Name'), required: "required" %>
  </div>

  <div class="form-group">
    <%= form.label t('Factory Manufacturer') %>
    <%= form.text_field :factory_manufacturer, id: :factory_manufacturer, class: "form-control", placeholder: t('Input Factory Manufacturer'), required: "required" %>
  </div>

  <div class="form-group">
    <%= form.label t('Load carrying capacity') %>
    <%= form.number_field :load_carrying_capacity, id: :elevator_type_load_carrying_capacity, class: "form-control", placeholder: t('Input Load carrying capacity'), required: "required" %>
  </div>

  <div class="form-group">
    <%= form.label t('Nominal speed') %>
    <%= form.number_field :nominal_speed, id: :elevator_type_nominal_speed, class: "form-control", placeholder: t('Input Nominal speed'), step: '0.01', required: "required" %>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/elevator_types/edit.html.erb
<h1><%= t('Editing Elevator Type') %></h1>

<%= render 'form', elevator_type: @elevator_type %>

<%= link_to t('Show'), @elevator_type %> |
<%= link_to t('Back'), elevator_types_path %>

app/views/elevator_types/index.html.erb
<% if notice %>
  <div class="alert alert-success" id="notice"><%= notice %></div>
<% end %>

<h1><%= t('Elevator Types') %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('Name') %></th>
      <th><%= t('Load carrying capacity') %></th>
      <th><%= t('Nominal speed') %></th>
      <th><%= t('Description') %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @elevator_types.order(name: :asc).each do |elevator_type| %>
      <% cache elevator_type do %>
        <tr>
          <td><%= elevator_type.name %></td>
          <td><%= elevator_type.load_carrying_capacity %></td>
          <td><%= elevator_type.nominal_speed %></td>
          <td><%= link_to t('Show'), elevator_type %></td>
          <td><%= link_to t('Edit'), edit_elevator_type_path(elevator_type) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('New Elevator Type'), new_elevator_type_path %>

app/views/elevator_types/new.html.erb
<h1><%= t('New Elevator Type') %></h1>

<%= render 'form', elevator_type: @elevator_type %>

<%= link_to t('Back'), elevator_types_path %>

app/views/elevator_types/show.html.erb
<% if notice %>
  <div class="alert alert-success" id="notice"><%= notice %></div>
<% end %>

<h1><%= t('Elevator Type') %></h1>

<p>
  <strong><%= t('Name') %>:</strong>
  <%= @elevator_type.name %>
</p>

<p>
  <strong><%= t('Factory Manufacturer') %>:</strong>
  <%= @elevator_type.factory_manufacturer %>
</p>


<p>
  <strong><%= t('Load carrying capacity') %>:</strong>
  <%= @elevator_type.load_carrying_capacity %>
</p>

<p>
  <strong><%= t('Nominal speed') %>:</strong>
  <%= @elevator_type.nominal_speed %>
</p>

<%= link_to t('Edit'), edit_elevator_type_path(@elevator_type) %> |
<%= link_to t('Back'), elevator_types_path %>