config/routes.rb
Rails.application.routes.draw do
  resources :service_events
  resources :problem_events
  get '/members/problem' => 'members#problem'
  get '/members/stat' => 'members#stat'
  get '/elevators/stat' => 'elevators#stat'
  get '/elevators/problem' => 'elevators#problem'
  get '/elevators/service' => 'elevators#service'
  resources :elevators
  resources :members
  resources :member_types
  resources :elevator_types
  resources :houses
  resources :management_companies
  get    '/login'     => 'sessions#new'
  post   '/login'     => 'sessions#create'
  # Выход
  get    '/logout'    => 'sessions#destroy'
  root 'sessions#new'
end

app/models/problem_event.rb
class ProblemEvent < ApplicationRecord
  belongs_to :elevator
  belongs_to :member
  
  def print_solved
    if solved == false
      'Нет'
    elsif solved.nil? 
      'Nill'
    else
      'Да'
    end
  end
end

app/controllers/problem_events_controller.rb
class ProblemEventsController < ApplicationController
  before_action :authorize
  before_action :set_problem_event, only: [:show, :edit, :update, :destroy]

  # GET /problem_events
  # GET /problem_events.json
  def index
    if elevator_repair_specialist?
      @problem_events = ProblemEvent.where("member_id = ? and planed_date <= ? or member_id = ? and planed_date IS ?", current_user.id, Time.now, current_user.id, nil)
    else
      @problem_events = ProblemEvent.all
    end
  end

  # GET /problem_events/1
  # GET /problem_events/1.json
  def show
  end

  # GET /problem_events/new
  def new
    @problem_event = ProblemEvent.new
  end

  # GET /problem_events/1/edit
  def edit
  end

  # POST /problem_events
  # POST /problem_events.json
  def create
    @problem_event = ProblemEvent.new(problem_event_params)
    @problem_event.solved = false
    respond_to do |format|
      if @problem_event.save
        format.html { redirect_to @problem_event, notice: t('Problem event was successfully created') }
        format.json { render :show, status: :created, location: @problem_event }
      else
        format.html { render :new }
        format.json { render json: @problem_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problem_events/1
  # PATCH/PUT /problem_events/1.json
  def update
    respond_to do |format|
      if @problem_event.update(problem_event_params)
        format.html { redirect_to @problem_event, notice: t('Problem event was successfully updated') }
        format.json { render :show, status: :ok, location: @problem_event }
      else
        format.html { render :edit }
        format.json { render json: @problem_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problem_events/1
  # DELETE /problem_events/1.json
  def destroy
    @problem_event.destroy
    respond_to do |format|
      format.html { redirect_to problem_events_url, notice: t('Problem event was successfully destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem_event
      @problem_event = ProblemEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_event_params
      params.require(:problem_event).permit(:elevator_id, :solved, :member_id, :description, :name, :planed_date)
    end
end

app/views/problem_events/_form.html.erb
<%= form_with(model: problem_event, local: true) do |form| %>
  <% if problem_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(problem_event.errors.count, "error") %> prohibited this problem_event from being saved:</h2>

      <ul>
      <% problem_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label t('Elevator') %>
    <%= form.label t('Serial number') %>
    <%= form.select :elevator_id, Elevator.all.collect {|m| [m.serial_number, m.id]}, {:selected => @problem_event.elevator_id}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t('Member') %>
    <%= form.select :member_id, Member.where(member_type_id: 4).collect {|m| [m.full_name, m.id]}, {:selected => @problem_event.member_id}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t('Name') %>
    <%= form.text_field :name, id: :problem_event_description, class: "form-control", placeholder: t('Input Name'), required: "required" %>
  </div>
  
  <div class="form-group">
    <%= form.label t('Planed date') %>
    <%= form.date_field  :planed_date, id: :planed_date, class: "form-control", placeholder: t('Input Planed date') %>  
  </div>

  <div class="form-group">
    <%= form.label t('Description') %>
    <%= form.text_area :description, id: :problem_event_description, class: "form-control", placeholder: t('Input Description'), required: "required" %>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/problem_events/edit.html.erb
<h1><%= t('Editing Problem Event') %></h1>

<%= render 'form', problem_event: @problem_event %>

<%= link_to t('Show'), @problem_event %> |
<%= link_to t('Back'), problem_events_path %>

app/views/problem_events/index.html.erb
<% if notice %>
  <div class="alert alert-success" id="notice"><%= notice %></div>
<% end %>

<h1><%= t('Problem Events') %></h1>

<h2><%= t('Not solveds') %></h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('Name') %></th>
      <th><%= t('Serial number') %></th>
      <th><%= t('Member') %></th>
      <th><%= t('Service events count') %></th>
      <th><%= t('Description') %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @problem_events.where(solved: false).each do |problem_event| %>
      <% cache problem_event do %>
        <tr>
          <td><%= problem_event.name %></td>
          <td><%= link_to problem_event.elevator.serial_number, problem_event.elevator %></td>
          <td><%= link_to problem_event.member.full_name, problem_event.member %></td>
          <td><%= ServiceEvent.where(problem_event: problem_event.id).count %></td>
          <td><%= link_to t('Show'), problem_event %></td>
          <td><%= link_to t('Edit'), edit_problem_event_path(problem_event) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to t('Problem stat')+t('by elevators'), '/elevators/stat' %>
<br>
<%= link_to t('Problem stat')+t('by members'), '/members/stat' %>
<br>

<%= link_to t('New Problem Event'), new_problem_event_path %>

<h2><%= t('Solveds') %></h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('Name') %></th>
      <th><%= t('Serial number') %></th>
      <th><%= t('Member') %></th>
      <th><%= t('Service events count') %></th>
      <th><%= t('Description') %></th>
    </tr>
  </thead>

   <tbody>
    <% @problem_events.where(solved: true).each do |problem_event| %>
      <% cache problem_event do %>
        <tr>
          <td><%= problem_event.name %></td>
          <td><%= link_to problem_event.elevator.serial_number, problem_event.elevator %></td>
          <td><%= link_to problem_event.member.full_name, problem_event.member %></td>
          <td><%= ServiceEvent.where(problem_event: problem_event.id).count %></td>
          <td><%= link_to t('Show'), problem_event %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/problem_events/new.html.erb
<h1><%= t('New Problem Event') %></h1>

<%= render 'form', problem_event: @problem_event %>

<%= link_to t('Back'), problem_events_path %>

app/views/problem_events/show.html.erb
<% if notice %>
  <div class="alert alert-success" id="notice"><%= notice %></div>
<% end %>

<h2><%= @problem_event.name %></h2>

<p>
  <strong><%= t('Address') %>:</strong>
  <%= @problem_event.elevator.house.address %>
</p>

<% if not @problem_event.planed_date.nil? %>
  <p>
    <strong><%= t('Planed date') %>:</strong>
    <%= Time.zone.at(@problem_event.planed_date).strftime("%F") %>
  </p>
<% end %>

<p>
  <strong><%= t('Elevator') %>:</strong>
  <%= @problem_event.elevator.id %>
</p>

<p>
  <strong><%= t('Solved') %>:</strong>
  <%= @problem_event.print_solved %>
</p>

<p>
  <strong><%= t('Member') %>:</strong>
  <%= @problem_event.member.full_name %>
</p>

<p>
  <strong><%= t('Description') %>:</strong>
  <%= @problem_event.description %>
</p>
<% if @problem_event.solved != true %>
  <%= link_to t('Edit'), edit_problem_event_path(@problem_event) %> |
<% end %>
<%= link_to t('Back'), problem_events_path %>

<h2><%= t('Service Events') + t('for this problem') %></h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('Name') %></th>
      <th><%= t('Member') %></th>
      <th><%= t('Description') %></th>
    </tr>
  </thead>

  <tbody>
    <% ServiceEvent.where(problem_event_id: @problem_event.id).each do |service_event| %>
      <tr>
        <td><%= service_event.name %></td>
        <td><%= link_to service_event.member.full_name, service_event.member %></td>
        <td><%= link_to t('Show'), service_event %></td>
      </tr>
    <% end %>
  </tbody>
</table>